/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_venuslobo;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ADMIN
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
         cargarArchivoSeleccionado();

        //hilo de la hora 
        hiloHora h = new hiloHora(texto_hora);
        Thread proceso1 = new Thread(h);
        proceso1.start();

        //hilo de la fecha
        hilofecha y = new hilofecha(texto_fecha);
        Thread proceso11 = new Thread(y);
        proceso11.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_rojo = new javax.swing.JPanel();
        panel_blanco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texto_fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texto_hora = new javax.swing.JLabel();
        boton_subir = new javax.swing.JButton();
        label_subir = new javax.swing.JLabel();
        label_archivo = new javax.swing.JLabel();
        barrita = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto = new javax.swing.JTextArea();
        boton_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_rojo.setBackground(new java.awt.Color(255, 51, 51));

        panel_blanco.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha de hoy:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora de hoy:");

        texto_hora.setText("jLabel3");

        javax.swing.GroupLayout panel_blancoLayout = new javax.swing.GroupLayout(panel_blanco);
        panel_blanco.setLayout(panel_blancoLayout);
        panel_blancoLayout.setHorizontalGroup(
            panel_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_blancoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panel_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_fecha)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(panel_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(texto_hora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panel_blancoLayout.setVerticalGroup(
            panel_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_blancoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(texto_fecha)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(texto_hora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boton_subir.setText("Subir archivo");
        boton_subir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_subirMouseClicked(evt);
            }
        });
        boton_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_subirActionPerformed(evt);
            }
        });

        label_subir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_subir.setForeground(new java.awt.Color(0, 0, 0));
        label_subir.setText("Subiendo archivo:");

        label_archivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_archivo.setForeground(new java.awt.Color(0, 0, 0));
        label_archivo.setText("ARCHIVO:");

        area_texto.setColumns(20);
        area_texto.setRows(5);
        jScrollPane1.setViewportView(area_texto);

        boton_guardar.setText("Guardar");
        boton_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_rojoLayout = new javax.swing.GroupLayout(panel_rojo);
        panel_rojo.setLayout(panel_rojoLayout);
        panel_rojoLayout.setHorizontalGroup(
            panel_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rojoLayout.createSequentialGroup()
                .addComponent(panel_blanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_rojoLayout.createSequentialGroup()
                        .addGroup(panel_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_rojoLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panel_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_subir)
                                    .addComponent(label_subir)
                                    .addComponent(barrita, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_rojoLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(label_archivo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_rojoLayout.createSequentialGroup()
                        .addGroup(panel_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_rojoLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_rojoLayout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(boton_guardar)))
                        .addContainerGap(207, Short.MAX_VALUE))))
        );
        panel_rojoLayout.setVerticalGroup(
            panel_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_rojoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(boton_subir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_subir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barrita, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(label_archivo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_guardar)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_rojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_rojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_subirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_subirActionPerformed

    private void boton_subirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_subirMouseClicked
        // TODO add your handling code here:

        JFileChooser cho = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
        cho.setFileFilter(filtro);
        int resultado = cho.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = cho.getSelectedFile(); // Guardar referencia al archivo seleccionado
            barrita HT = new barrita(barrita, archivoSeleccionado, area_texto, this);
            HT.start();
        }
    }//GEN-LAST:event_boton_subirMouseClicked

    // Método para cargar el contenido del archivo seleccionado al JTextArea
    private void cargarArchivoSeleccionado() {
        if (archivoSeleccionado != null) {
            try {
                FileReader fr = new FileReader(archivoSeleccionado);
                BufferedReader br = new BufferedReader(fr);
                StringBuilder contenido = new StringBuilder();
                String linea;
                while ((linea = br.readLine()) != null) {
                    contenido.append(linea).append("\n");
                }
                br.close();
                area_texto.setText(contenido.toString());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo seleccionado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void boton_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardarMouseClicked
        // TODO add your handling code here:
        if (archivoSeleccionado != null) { // Verificar si se ha seleccionado un archivo antes
            String texto = area_texto.getText();
            try {
                FileWriter fw = new FileWriter(archivoSeleccionado);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(texto);
                bw.close();
                JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar los cambios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún archivo para guardar los cambios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    private File archivoSeleccionado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_texto;
    private javax.swing.JProgressBar barrita;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JButton boton_subir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_archivo;
    private javax.swing.JLabel label_subir;
    private javax.swing.JPanel panel_blanco;
    private javax.swing.JPanel panel_rojo;
    private javax.swing.JLabel texto_fecha;
    private javax.swing.JLabel texto_hora;
    // End of variables declaration//GEN-END:variables
}
